### ISSUE TITLE
Implement Search views

### ISSUE THREAD

**Issue by kyanzwick** [GreenMeteor/verified#22] opened 2023-04-29 18:04 UTC
**Is your feature request related to a problem? Please describe.**
No way to know if space or user is verified in "search" or "my spaces"

**Describe the solution you'd like**
To have the verified tick displayed next to spaces and users in the search and "my spaces"

**Additional context**
Would help with being able to tell which users and spaces are verified. Especially when someone is searching for the real user or space.

**Comment by ArchBlood** [comment] 2023-04-30 02:44
I can't say for sure that this will make it into the core of the Verified module immediately as there are more important functions being implemented at this time.

**Comment by ArchBlood** [comment] 2023-04-30 02:57
But I'd like to also ask @felixhahnweilheim opinion if it's really necessary as most users would know to click on the user in a post rather than paying much mind to the sidebar. :thinking:

**Comment by felixhahnweilheim** [comment] 2023-04-30 11:33
I would add it to the search but not to the My spaces picker.

The space picker is quite narrow and you can use the Spaces page and filter by status "Member".

**Comment by ArchBlood** [comment] 2023-04-30 18:51
> I would add it to the search but not to the My spaces picker.
> 
> The space picker is quite narrow and you can use the Spaces page and filter by status "Member".

I agree, implementing within the my space drop-down menu doesn't really matter or not as it's already implemented into the Spaces directory, search on the other hand can be very powerful and useful.

**Comment by felixhahnweilheim** [comment] 2023-05-02 16:44
I'm just trying to overwrite the widget `humhub\modules\user\widgets\UserWall` (showing a user in search) and  `humhub\modules\space\widgets\Wall` (showing a space in search).
The problem is that both extend `\yii\base\Widget`, not `humhub\components\Widget`. So we cannot overwrite it the same way we overwrite the others (with the EVENT_CREATE event).

**Comment by ArchBlood** [comment] 2023-05-02 17:14
> I'm just trying to overwrite the widget `humhub\modules\user\widgets\UserWall` (showing a user in search) and `humhub\modules\space\widgets\Wall` (showing a space in search). The problem is that both extend `\yii\base\Widget`, not `humhub\components\Widget`. So we cannot overwrite it the same way we overwrite the others (with the EVENT_CREATE event).

Maybe we can create a request on the GitHub repo for a refactor of these widgets so that we can extend them?

**Comment by felixhahnweilheim** [comment] 2023-05-03 14:28
I have prepared a branch `search-views` which should be merged after the next HumHub release.

**Comment by ArchBlood** [comment] 2023-06-03 07:25
> I have prepared a branch `search-views` which should be merged after the next HumHub release.

Next we'll need to update the `search-views` branch with the current `main` branch and create a draft P/R then wait for v1.15-beta.1 to be released.

**Comment by ArchBlood** [comment] 2023-07-31 16:21
The first beta has been released for HumHub 1.15 so I believe we can start getting ready to push for the next update for this module to the marketplace.

**Closed** 2023-08-01 07:50 UTC
Labels: Status: TBA, Type: Enh
